### ISSUE TITLE
invalidateQueries is not working

### ISSUE THREAD

**Issue by iamhaaamed** [D-James-GH/cached_query#1]
My `invalidateQueries` is not working in mutations. This is my sample code:
```
import 'package:cached_query_flutter/cached_query_flutter.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:to_do_app/models/todo.dart';

class TodosListScreen extends StatefulWidget {
  const TodosListScreen({Key? key}) : super(key: key);

  @override
  State<TodosListScreen> createState() => _TodoListScreenState();
}

class _TodoListScreenState extends State<TodosListScreen> {
  @override
  Widget build(BuildContext context) {
    final query = Query<List<Todo>>(
      queryFn: () async =>
          ((await Dio().get("http://localhost:3000/todos")).data as List)
              .map((e) => Todo.fromJson(e))
              .toList(),
      key: ["todos"],
    );

    final toggleTodoMutation = Mutation<dynamic, Todo>(
      invalidateQueries: ['todos'],
      refetchQueries: ['todos'],
      queryFn: (todo) async => ((await Dio()
              .patch("http://localhost:3000/todos/${todo.id}", data: todo))
          .data),
    );

    return QueryBuilder(
      query: query,
      builder: (BuildContext context, QueryState<Object?> state) {
        var todos = state.data as List<Todo>;
        return Column(
          children: [
            if (state.data != null)
              Expanded(
                child: ListView.builder(
                  itemCount: (todos).length,
                  itemBuilder: (context, index) => Row(
                    children: [
                      Expanded(
                        child: CheckboxListTile(
                          value: (todos)[index].completed,
                          onChanged: (newValue) async {
                            Todo todo = (todos)[index];
                            await toggleTodoMutation.mutate(
                                todo.copyWith(completed: !todo.completed!));
                          },
                        ),
                      ),
                      Text((todos)[index].body!),
                    ],
                  ),
                ),
              ),
          ],
        );
      },
    );
  }
}

```
only when I add   
`onSuccess: ((res, arg) => {query.refetch()}) `
to 
`toggleTodoMutation`
it is working.

**Comment by D-James-GH** [comment]
Hi @iamhaaamed 

At the moment there is no fuzzy matching on keys.
Your key in your query is not quite the same as the key you are trying to invalidate. The key in the query is a List `["todos"]`. Then in your mutation the invalidation the key is just a string.

Note, refetchQueries and invalidateQueries takes a List of keys. 
So to make your sample code work you can change the query key to "todos" OR change the refetchQueries argument to `[["todos"]]`. 

So the new query would become: 
```dart
final query = Query<List<Todo>>(
      queryFn: () async =>
          ((await Dio().get("http://localhost:3000/todos")).data as List)
              .map((e) => Todo.fromJson(e))
              .toList(),
      // Changed to just a string
      key: "todos",
    );
```


In the future I would like to introduce fuzzy matching on keys, but for now the keys must match exactly.

Let me know if you have any questions

**Comment by iamhaaamed** [comment]
Thank you for your help, but I don't understand why `invalidateQueries` is not working and why I should call `refetchQueries`?
In `react-query` in the `onSuccess` of the mutations, we can call `invalidateQueries` and it will automatically calling the relevant queries and updates the cache, but here it is not do the same like react-query.

**Comment by D-James-GH** [comment]
`InvalidateQueries` sets the query as stale and will be refetched next time a call to the queryFn happens, this might be useful if you have a large `refetchDuration` on a query and need to remove the duration. 
`refetchQueries` is the same as the react-query version. It will refetch the query keys immediately. 
In your case you do not need the `invalidateQueries` as you just want to re-fetch the queries immediately.

**Comment by iamhaaamed** [comment]
Got it, thank you.
