### ISSUE TITLE
Advice for implementing Revalidate on Interval

### ISSUE THREAD

**Issue by zakandrewking** [D-James-GH/cached_query#16]
SWR supports [Revalidate on Interval](https://swr.vercel.app/docs/revalidation#revalidate-on-interval), which makes it easy to poll for changes in a view that's currently on screen.

Does cached_query support anything like this? Or is the best approach to create our own interval timer and manually revalidate the cache?

Would you be open to a PR that creates that functionality?

**Comment by D-James-GH** [comment]
Cached Query does not currently support this feature, however, calling `query.refetch()` inside a `Timer. periodic` would achieve a similar result and this can be easily be cancelled using the dispose method of a widget. 

I am open to adding something like this, however, I do have some concerns. The architecture of React is quite different to flutter. In React you always (and have to) use hooks inside the UI component. This has the benefit of the query (useSwr) having direct access to the lifecycle events of a component. In other words, swr always knows when a query goes out of scope. This is not necessarily the same in flutter/cached_query. In Flutter it is encouraged to move business logic out of the UI and into blocs where access to component lifecycle events is limited. So my main concern is that it will be difficult to know when to stop "revalidate on interval" as without careful architectural practices a query in a bloc may never go out of scope (eg. it's in a top-level bloc). 

We may be able to get around this by documentation and examples. What do you think?

**Comment by zakandrewking** [comment]
Thanks for the quick response - that makes perfect sense. It does seem flutter specific, and would probably look like a widget that can hook into the flutter lifecycle. I'll see if we come up with anything that seems generalizable, but I'll close this in the meantime.
