### ISSUE TITLE
rxdart dependency issue

### ISSUE THREAD

**Issue by Jaew00Shin** [D-James-GH/cached_query#37]
Because cached_query_flutter >=2.1.1 depends on cached_query ^2.0.4 which depends on rxdart ^0.27.7, cached_query_flutter >=2.1.1 requires rxdart ^0.27.7.
So, because rock2you depends on both cached_query_flutter ^2.1.1 and rxdart ^0.28.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on rxdart: flutter pub add rxdart:^0.27.7

Could you update your rxdart version?

**Comment by D-James-GH** [comment]
sure, I'll move the update to rxdart to version 3 of cached query which will require a later dart

**Comment by D-James-GH** [comment]
updated with https://github.com/D-James-GH/cached_query/releases/tag/cached_query-v2.0.5

https://pub.dev/packages/cached_query_flutter version: `cached_query_flutter: ^2.1.2`
