### ISSUE TITLE
Feature: Multiple Instances for CachedQuery

### ISSUE THREAD

**Issue by xeinebiu** [D-James-GH/cached_query#42]
Hi,

I’d like to request the ability to create multiple `CachedQuery` instances, instead of just using a singleton. This would make managing queries easier in larger apps and prevent potential conflicts when using third-party libraries that also use CachedQuery.

### Example Use Cases

1. **Handling Different Data Sources:**

   You might want to separate caches for different types of data:

   ```dart
   // might havr differetent cacheTime, refetch on connection, etc ...
   final apiCached =
   final userQuery = apiCached.createQuery(...);
 
   final productCached =
   final productQuery = productaCached.createQuery(...);
   ```

2. **Scoping Queries to Specific Parts of the App:**

   In larger projects, we might want to manage queries in different modules independently:

   ```dart
   final moduleAQuery = moduleACachedQuery.createQuery(...);
   final moduleBQuery = moduleBCachedQuery.createQuery(...);
   ```

3. **Testing Queries Independently:**

   Having separate instances would make testing easier by isolating queries:

   ```dart
   final testQuery = CachedQuery(...).createQuery(...);
   ```

4. **Avoiding Conflicts with Third-Party Libraries:**

   Third-party libraries might also use `CachedQuery`, and with a singleton, we could face key conflicts between our app's queries and those used by the library. With separate instances, we could avoid this problem..

----

Edit

```dart
// compatible with current API
final userNotesQuery = Query(key, queryFn, ..., cache: <Cached Query Instance>);

// Alternative
final userNotesQuery = <Cached Query Instance>.createQuery(...)
```

**Comment by D-James-GH** [comment]
Interesting, when I originally designed the global cache I had it in a provider. However, the architecture we generally use is where our data layer to be separate to our UI layer. So a singleton was a better fit due to the fact you can use it anywhere. 

I think a good starting point for implementation will be to take inspiration to how https://pub.dev/packages/get_it handles scoping. Or just use get_it, although I would rather not add dependencies if possible. 

@xeinebiu do you have any thoughts on this?

**Comment by xeinebiu** [comment]
> Interesting, when I originally designed the global cache I had it in a provider. However, the architecture we generally use is where our data layer to be separate to our UI layer. So a singleton was a better fit due to the fact you can use it anywhere.
> 
> I think a good starting point for implementation will be to take inspiration to how https://pub.dev/packages/get_it handles scoping. Or just use get_it, although I would rather not add dependencies if possible.
> 
> @xeinebiu do you have any thoughts on this?

I've used Get_It and I like it. I would really appreciate having the option to manage multiple instances of "cached_query," similar to what is shown in the examples:

```dart
final userNotes = Query(..., cache: moduleACachedQuery);
final globalUserNotes = Query(...); // Not specifying the cache will use the global instance as it is currently
```

ReactQuery offers the ability to manage multiple instances in a similar way.

If you need any help, let me know and I'll try to find some time to contribute.

**Comment by D-James-GH** [comment]
okay, makes sense. Adding an option to pass a custom client would be a good and simple starting point. This would mean that the user of the library would have to keep a reference to the custom client by them selves eg, using a provider or a singleton of their own. There would be no scoping like in react as we are not using the build context to scope the client.

eg. in react you can wrap a section of the app with a QueryClientProvider. `useQuery` will find the closest client. This will not be available.

**Comment by xeinebiu** [comment]
> okay, makes sense. Adding an option to pass a custom client would be a good and simple starting point. This would mean that the user of the library would have to keep a reference to the custom client by them selves eg, using a provider or a singleton of their own. There would be no scoping like in react as we are not using the build context to scope the client.
> 
> eg. in react you can wrap a section of the app with a QueryClientProvider. `useQuery` will find the closest client. This will not be available.

QueryClientProvider is not a must I would say. Only a possibility to provide a "Cached Instance" to Queries or Mutations instead of using the Global/Singleton one.

**Comment by D-James-GH** [comment]
Updated with the following versions: 
```yaml
cached_query: ^2.1.0
cached_query_flutter: ^2.3.0
```

**Comment by xeinebiu** [comment]
> Updated with the following versions:
> 
> ```yaml
> cached_query: ^2.1.0
> cached_query_flutter: ^2.3.0
> ```
> 
> https://cachedquery.dev/docs/guides/query#local-cache
> 
> Full example: https://github.com/D-James-GH/cached_query/tree/main/examples/multiple_caches

Thanks for your time, apprecite the new feature. <3
