### ISSUE TITLE
How cached_query_flutter handle nested query?

### ISSUE THREAD

**Issue by siamahnaf** [D-James-GH/cached_query#47]
I am from React World. This is very nice package. I read full documentation, but I have one question-

1. Suppose, I have a nested widget. Main Widget is Home Page Widget, into that home page widget I call another widget.
2. If I already handle loading state, error message and state.data is not null checking on home Widget. Should I redo same thing on my nested another widget which I call onto home widget?
3. Is there any way to get fetched data in nested widget without using QueryBuilder widget everywhere?

**Comment by D-James-GH** [comment]
Hey, 

> If I already handle loading state, error message and state.data is not null checking on home Widget. Should I redo same thing on my nested another widget which I call onto home widget?

In general yeah, probably, although this would depend on how you are architecting your application. A `QueryBuilder` is similar to `useQuery` if you are coming from react. You could take the data from a query and passing down to the nested widgets via props or context if you like or, like you say, re-use the null check logic from your home page widget. 

>Is there any way to get fetched data in nested widget without using QueryBuilder widget everywhere?

Yeah there are a couple of ways: 
1. you could have a function that creates the query and re-use the stream that's part of the query. 
```dart
Query postQuery(String id){
  return Query(
    key: 'posts/$id',
    queryFn: ...,
  );
}
```
As long as you call the `postQuery` function with the same ID each time it will always return the say instance of the query, so you can have access to the data/status. 

2. Use one of the methods on `CachedQuery.instance`
There are a couple of methods that allow you to retrieve a query: `whereQuery` for finding a list of queries and getQuery which takes a query key. 

Both of these methods work well from anywhere as CachedQuery is a singleton
