### ISSUE TITLE
Graphql 

### ISSUE THREAD

**Issue by SOMONSOUM** [D-James-GH/cached_query#5]
Does it support Graphql?

If it support with Graphql. Could you implement it with query and mutation as a sample?
Thank

**Comment by D-James-GH** [comment]
Hi, 
Cached query is a method for cached async requests. This means that it could definitely be used to cache graphql requests. However, it is not a graphql client. If you wish to cache requests using Cached Query you will need to use an external client. I personally have only used graphql in react, however, for dart [flutter_graphql](https://pub.dev/packages/graphql_flutter) seams to be the most popular, it also seams to be able cache requests similar to CachedQuery. 

Let me know if you have any questions.

**Comment by SOMONSOUM** [comment]
Thank for your reply
I personally don't like the way that flutter_graphql do for caching data that's why I'm seeking a suitable one that similar to Apollo Client and React Query do.

**Comment by SOMONSOUM** [comment]
Could you use flutter_graphql as a Graphql client + Cached Query as a sample?

**Comment by D-James-GH** [comment]
Ahh, thats understandable. Well, the caching in Cached Query is very similar to react query, for example, in react query you would also have to use an external graphql client. Unfortunately I personally l can't recommend any graphql clients for flutter as I haven't used graphql in flutter before. 

I may do a full example at some point, however, as flutter_graphql already has caching built in it is low on my priority list at the moment. 

For now though, something like the following could work (the graphql code is taken from the [graphql](https://pub.dev/packages/graphql#query) package):
```dart
import 'package:graphql/client.dart';
//
//...some other code
//
const String readRepositories = r'''
  query ReadRepositories($nRepositories: Int!) {
    viewer {
      repositories(last: $nRepositories) {
        nodes {
          __typename
          id
          name
          viewerHasStarred
        }
      }
    }
  }
''';
Query<ResponseModel> getGraphqlResponse(int nRepositories) {
  return Query<PostModel>(
    key: "graphql",
    queryFn: () async {
      final QueryOptions options = QueryOptions(
        document: gql(readRepositories),
        variables: <String, dynamic>{
          'nRepositories': nRepositories,
        },
      );
      final QueryResult result = await client.query(options);

      // serialise the result of the graphql response into a dart object or return as a map
      return ResponseModel.fromJson(result.data);
    },
  );
}
```
The above code will use graphql to fetch the data then cache the result in cached query.
