### ISSUE TITLE
Improve callback types and IDE integration

### ISSUE THREAD

**Issue by clragon** [D-James-GH/cached_query#54]
### Is your feature request related to a problem? Please describe.
Currently, all Callback types inside the package use unnamed parameters, e.g.
`typedef OnInfiniteQuerySuccessCallback<T> = void Function(T);`.
This is a neutral choice but uncommon in the dart ecosystem. The reason for this is that IDE autocompletion will use the name of the function type to insert code snippets.

![image](https://github.com/user-attachments/assets/aab8703a-80f1-47d8-9ab6-a3f3d71d1a75)
This pattern is so common that VScode does not account for a scenario where a name is absent, and therefore inserts an awkward space where it would follow.

### Describe the solution you'd like
Refactor all function types to also include parameter names. 
A simple example would be
`typedef OnInfiniteQuerySuccessCallback<T> = void Function(T data);`.

**Comment by D-James-GH** [comment]
Implemented in cached_query_flutter: ^2.4.1
